// Writes one version of one of the two bun-apps (see ../README.md):
//
//   node gen.mjs <plain|mixed|lazy> <1.0.0|1.1.0> <out-dir>
//
// The three apps have the same six ES modules, a local CommonJS
// dependency and the real npm package ms@2.1.3:
//
//   plain — every module imported statically: Bun writes NO lazy-init
//           module at all;
//   mixed — two of the six (archive, codec) reached only through require()
//           from a CommonJS module (loader.cjs): Bun wraps exactly those
//           two in lazy inits, the other four stay eager;
//   lazy  — all six reached only through loader.cjs, and the entry only
//           calls it: every module lazy, a two-statement entry — the
//           shape the module markers describe (Claude Code's).
//
// Deterministic: same arguments, same bytes.
import * as fs from "node:fs";
import * as path from "node:path";

const [app, version, out] = process.argv.slice(2);
if (!["plain", "mixed", "lazy"].includes(app) || !["1.0.0", "1.1.0"].includes(version) || !out) {
  console.error("usage: node gen.mjs <plain|mixed|lazy> <1.0.0|1.1.0> <out-dir>");
  process.exit(2);
}
const v2 = version === "1.1.0";

// Module name, report tag, seed. Each module is a chain of small functions
// that reference each other and their own table only — no module reads
// another, so the reference graph has a clean seam at every module edge.
const MODULES = [
  ["units", "UNITS", 3],
  ["palette", "PALETTE", 5],
  ["archive", "ARCHIVE", 7],
  ["codec", "CODEC", 11],
  ["ledger", "LEDGER", 13],
  ["router", "ROUTER", 17]
];
const STEPS = 40;
const LAZY = new Set(
  { plain: [], mixed: ["archive", "codec"], lazy: MODULES.map(([name]) => name) }[app]
);

function moduleSource(name, tag, seed) {
  const table = `${tag}_TABLE`;
  const lines = [
    `// ${name}.js — generated by gen.mjs (${app} app, v${version})`,
    `const ${table} = [];`,
    "for (let i = 0; i < 8; i++) {",
    `  ${table}.push((i * ${seed} + 3) % 17);`,
    "}",
    "",
    `export function ${name}Step0(x) {`,
    `  return (x * ${seed} + ${table}[x % 8]) % 101;`,
    "}"
  ];
  for (let k = 1; k < STEPS; k++) {
    const prev = `${name}Step${k - 1}`;
    const back = `${name}Step${Math.max(0, k - 2)}`;
    lines.push(
      `export function ${name}Step${k}(x) {`,
      `  return (${prev}(x) + ${back}(x + ${k}) * ${(k % 5) + 1}) % 1009;`,
      "}"
    );
  }
  // v1.1.0: palette and archive change their report (a real code change
  // in an eager and in a lazy module).
  const changed = v2 && (name === "palette" || name === "archive");
  lines.push(
    `export function ${name}Report(n) {`,
    changed
      ? `  return "${tag}#" + String(${name}Step${STEPS - 1}(n)).padStart(4, "0");`
      : `  return "${tag}#" + ${name}Step${STEPS - 1}(n);`,
    "}",
    ""
  );
  return lines.join("\n");
}

const CLOCK = `"use strict";
// A local CommonJS dependency (vendor extraction).
var origin = 1000;
function tick(n) {
  return origin + n * 60;
}
${v2 ? "function tock(n) {\n  return origin - n;\n}\n" : ""}
module.exports = { tick${v2 ? ", tock" : ""} };
`;

// A CommonJS module that requires the lazy ES modules: each only
// initializes on its first call, so Bun wraps each in a lazy init.
function loaderSource() {
  const lines = ["// loader.cjs — generated by gen.mjs: requires its modules lazily."];
  for (const name of LAZY) {
    lines.push(
      `function ${name}Report(n) {`,
      `  const { ${name}Report: report } = require("./${name}.js");`,
      "  return report(n);",
      "}"
    );
  }
  lines.push("", `module.exports = { ${[...LAZY].map((n) => `${n}Report`).join(", ")} };`, "");
  return lines.join("\n");
}

// The lazy app's entry only calls the loader: its whole report runs in
// the loader's caller, and the bundle's eager tail is two statements.
function lazyMainSource() {
  return [
    `// main.js — generated by gen.mjs (${app} app, v${version})`,
    'import loader from "./loader.cjs";',
    'import { report } from "./report.cjs";',
    "",
    "report(loader);",
    ""
  ].join("\n");
}

const REPORT = `// report.cjs — generated by gen.mjs: prints the lazy app's report.
const ms = require("ms");
const clock = require("./vendor/clock.cjs");
function report(loader) {
  const lines = [
${MODULES.map(([name]) => `    \`${name}: \${loader.${name}Report(${name.length})}\`,`).join("\n")}
    \`ms: \${ms(90000)} \${ms("2h")}\`,
    \`clock: \${clock.tick(3)}\`
  ];
  for (const line of lines) {
    console.log(line);
  }
}
module.exports = { report };
`;

function mainSource() {
  if (app === "lazy") return lazyMainSource();
  const imports = [];
  const reports = [];
  for (const [name] of MODULES) {
    if (LAZY.has(name)) continue;
    imports.push(`import { ${name}Report } from "./${name}.js";`);
    reports.push(`  \`${name}: \${${name}Report(${name.length})}\`,`);
    // The loader comes right after palette: units and palette are emitted
    // BEFORE the lazy modules, ledger and router after them.
    if (name === "palette" && LAZY.size > 0) {
      imports.push('import loader from "./loader.cjs";');
      for (const lazy of LAZY) {
        reports.push(`  \`${lazy}: \${loader.${lazy}Report(${lazy.length})}\`,`);
      }
    }
  }
  return [
    `// main.js — generated by gen.mjs (${app} app, v${version})`,
    ...imports,
    'import ms from "ms";',
    'import clock from "./vendor/clock.cjs";',
    "",
    "const lines = [",
    ...reports,
    "  `ms: ${ms(90000)} ${ms(\"2h\")}`,",
    "  `clock: ${clock.tick(3)}`",
    "];",
    "for (const line of lines) {",
    "  console.log(line);",
    "}",
    ""
  ].join("\n");
}

const pkg = {
  name: `bun-${app}-fixture`,
  version,
  private: true,
  dependencies: { ms: "2.1.3" }
};

fs.mkdirSync(path.join(out, "src", "vendor"), { recursive: true });
fs.writeFileSync(path.join(out, "package.json"), `${JSON.stringify(pkg, null, 2)}\n`);
for (const [name, tag, seed] of MODULES) {
  fs.writeFileSync(path.join(out, "src", `${name}.js`), moduleSource(name, tag, seed));
}
fs.writeFileSync(path.join(out, "src", "vendor", "clock.cjs"), CLOCK);
if (LAZY.size > 0) fs.writeFileSync(path.join(out, "src", "loader.cjs"), loaderSource());
if (app === "lazy") fs.writeFileSync(path.join(out, "src", "report.cjs"), REPORT);
fs.writeFileSync(path.join(out, "src", "main.js"), mainSource());
