//! Propagation tests (WP2.1's post-pass). Two layers:
//!
//! 1. PARITY against the frozen TS probe
//!    (`test/parity/wp21-propagation-frozen.json`, generated by
//!    `test/parity/wp21-propagation-probe.mjs`): the TS hash-only cascade's
//!    matches/ambiguous flow into the Rust `propagate` and the outcome AND
//!    the mutated maps must reproduce. The structuralHash bytes are
//!    oxc-vs-babel artifacts (the WP1.4 gate), but the precondition rides
//!    the frozen SESSION-ID pairs, so no hash comparison is needed — the
//!    Rust graphs are built from the same texts.
//! 2. UNIT tests for the rung semantics, mirroring
//!    `src/analysis/propagation.test.ts`. The TS tests drive the real
//!    cascade; here the same hash-only precondition class is built directly
//!    (unique hashes match, same-hash groups park in ambiguous with the
//!    bucket in graph-row order — the TS cascade's candidate order), so
//!    every expectation is about the PROPAGATION, not the cascade.

use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::fs;

use oxc_allocator::Allocator;

use crate::graph::build_unified_graph;
use crate::hash::serialize::SymbolTables;
use crate::ingest::Ingest;
use crate::matching::{FingerprintIndex, build_fingerprint_index};
use crate::propagation::{
    AmbiguousMatches, ExternalRefEvidence, PropagationOptions, PropagationOutcome, propagate,
};

// ---------------------------------------------------------------------------
// Harness
// ---------------------------------------------------------------------------

/// Parse + graph + tables + index for BOTH sides, handed to the assertions
/// inside the scope that owns both arenas (the Semantic borrows the
/// allocator, so it cannot leave).
fn with_pair<T>(
    old_code: &str,
    new_code: &str,
    run: impl FnOnce(&FingerprintIndex<'_>, &FingerprintIndex<'_>) -> T,
) -> T {
    let old_allocator = Allocator::default();
    let old_ingest = Ingest::parse(&old_allocator, old_code, "input.js");
    assert!(
        old_ingest.errors.is_empty(),
        "old must parse: {:?}",
        old_ingest.errors
    );
    let old_tables = SymbolTables::build(&old_ingest.semantic);
    let old_graph = build_unified_graph(
        &old_ingest.semantic,
        old_ingest.program,
        "input.js",
        &[],
        None,
        None,
    );
    let old_index = build_fingerprint_index(&old_graph, &old_ingest.semantic, &old_tables);

    let new_allocator = Allocator::default();
    let new_ingest = Ingest::parse(&new_allocator, new_code, "input.js");
    assert!(
        new_ingest.errors.is_empty(),
        "new must parse: {:?}",
        new_ingest.errors
    );
    let new_tables = SymbolTables::build(&new_ingest.semantic);
    let new_graph = build_unified_graph(
        &new_ingest.semantic,
        new_ingest.program,
        "input.js",
        &[],
        None,
        None,
    );
    let new_index = build_fingerprint_index(&new_graph, &new_ingest.semantic, &new_tables);

    run(&old_index, &new_index)
}

/// The session id of the (uniquely named) old/new function.
fn session_of(graph: &crate::graph::UnifiedGraph, name: &str) -> String {
    graph
        .functions
        .iter()
        .find(|f| f.name == name)
        .unwrap_or_else(|| panic!("no function named {name}"))
        .session_id
        .clone()
}

/// The same-hash candidates of one old function, in new-graph row order —
/// the TS cascade's ambiguous candidate order (the bucket lists in
/// functions-map order).
fn same_hash_candidates(
    old_index: &FingerprintIndex<'_>,
    new_index: &FingerprintIndex<'_>,
    old_session: &str,
) -> Vec<String> {
    let entry = old_index
        .entries
        .iter()
        .find(|entry| entry.session_id == old_session)
        .unwrap_or_else(|| panic!("{old_session} is not an index row"));
    let hash = entry.fingerprint.structural_hash();
    new_index
        .entries
        .iter()
        .filter(|entry| entry.fingerprint.structural_hash() == hash)
        .map(|entry| entry.session_id.clone())
        .collect()
}

/// The TS `matchFunctions(..., { maxCascadeDepth: 0 })` precondition class:
/// unique-hash functions match, same-hash groups park in ambiguous.
fn hash_only_precondition(
    old_index: &FingerprintIndex<'_>,
    new_index: &FingerprintIndex<'_>,
) -> (HashMap<String, String>, AmbiguousMatches) {
    let mut matches = HashMap::new();
    let mut ambiguous = AmbiguousMatches::new();
    for entry in &old_index.entries {
        let candidates = same_hash_candidates(old_index, new_index, &entry.session_id);
        if candidates.len() == 1 {
            matches.insert(entry.session_id.clone(), candidates[0].clone());
        } else if candidates.len() > 1 {
            ambiguous.insert(entry.session_id.clone(), candidates);
        }
    }
    (matches, ambiguous)
}

/// Like `hash_only_precondition`, but the ambiguous entries are inserted in
/// the REQUESTED old-function-name order — the ambiguous insertion order is
/// decision input (a resolution's claim affects later entries of the same
/// iteration), so the multi-iteration tests pin it.
fn ordered_precondition(
    old_index: &FingerprintIndex<'_>,
    new_index: &FingerprintIndex<'_>,
    ambiguous_order: &[&str],
) -> (HashMap<String, String>, AmbiguousMatches) {
    let mut matches = HashMap::new();
    let mut ambiguous = AmbiguousMatches::new();
    for name in ambiguous_order {
        let session = session_of(old_index.graph, name);
        let candidates = same_hash_candidates(old_index, new_index, &session);
        assert!(candidates.len() > 1, "{name} is not ambiguous");
        ambiguous.insert(session, candidates);
    }
    for entry in &old_index.entries {
        if ambiguous.contains(&entry.session_id) {
            continue;
        }
        let candidates = same_hash_candidates(old_index, new_index, &entry.session_id);
        assert_eq!(
            candidates.len(),
            1,
            "{} has no unique hash-only partner",
            entry.session_id
        );
        matches.insert(
            entry.session_id.clone(),
            candidates.into_iter().next().unwrap(),
        );
    }
    (matches, ambiguous)
}

fn run_default(
    old_index: &FingerprintIndex<'_>,
    new_index: &FingerprintIndex<'_>,
    matches: &mut HashMap<String, String>,
    ambiguous: &mut AmbiguousMatches,
) -> PropagationOutcome {
    propagate(
        matches,
        ambiguous,
        old_index,
        new_index,
        PropagationOptions::default(),
    )
}

/// The exp066 guard: the per-rung counts must sum to the total.
fn assert_rungs_sum(outcome: &PropagationOutcome) {
    assert_eq!(
        outcome.by_rung.total(),
        outcome.resolved,
        "rungs must sum to the resolved total"
    );
}

/// TS `assertCallGraphConsistency` (propagation.test.ts :545): matched
/// pairs must agree with the call-graph topology — if an old function
/// calls callee X (matched to X'), the matched new function must call X'.
fn assert_call_graph_consistency(
    old_index: &FingerprintIndex<'_>,
    new_index: &FingerprintIndex<'_>,
    matches: &HashMap<String, String>,
) {
    let old_graph = old_index.graph;
    let new_graph = new_index.graph;
    let new_row_by_session: HashMap<&str, usize> = new_graph
        .functions
        .iter()
        .enumerate()
        .map(|(row, f)| (f.session_id.as_str(), row))
        .collect();
    let old_session_by_span: HashMap<(u32, u32), &str> = old_graph
        .functions
        .iter()
        .map(|f| ((f.span.start, f.span.end), f.session_id.as_str()))
        .collect();
    let new_session_by_span: HashMap<(u32, u32), &str> = new_graph
        .functions
        .iter()
        .map(|f| ((f.span.start, f.span.end), f.session_id.as_str()))
        .collect();
    for f in &old_graph.functions {
        let Some(new_id) = matches.get(&f.session_id) else {
            continue;
        };
        let new_row = new_row_by_session[new_id.as_str()];
        let new_callees: BTreeSet<&str> = new_graph.functions[new_row]
            .internal_callees
            .iter()
            .filter_map(|span| new_session_by_span.get(&(span.start, span.end)).copied())
            .collect();
        for callee in &f.internal_callees {
            let old_callee = old_session_by_span
                .get(&(callee.start, callee.end))
                .copied();
            let Some(matched_callee) = old_callee.and_then(|session| matches.get(session)) else {
                continue;
            };
            assert!(
                new_callees.contains(matched_callee.as_str()),
                "matched {}->{} but callee mapping inconsistent: old callee {} matched to {} which is not called by {}",
                f.session_id,
                new_id,
                old_callee.unwrap(),
                matched_callee,
                new_id
            );
        }
    }
}

/// Test-only: the mutated matches map, order-normalized for comparison (the
/// TS map order is insertion order and the comparison sorts both sides — a
/// hash map's iteration order cannot matter here).
#[allow(clippy::iter_over_hash_type)]
fn normalized_matches(matches: &HashMap<String, String>) -> BTreeMap<String, String> {
    matches
        .iter()
        .map(|(k, v)| (k.clone(), v.clone()))
        .collect()
}

// ---------------------------------------------------------------------------
// Fixtures (the TS test file's, with unique names where a lookup needs one)
// ---------------------------------------------------------------------------

/// TS :29-49 — two structurally identical wrappers calling different
/// (unique) callees.
const CALLEE_OLD: &str = r#"
function wrapper1() { return uniqueA(); }
function wrapper2() { return uniqueB(); }
function uniqueA() { return "hello"; }
function uniqueB(x) { return x + 1; }
"#;
const CALLEE_NEW: &str = r#"
function w1() { return uA(); }
function w2() { return uB(); }
function uA() { return "hello"; }
function uB(x) { return x + 1; }
"#;

/// TS :79-98 — two identical leaf functions called by different (unique)
/// callers.
const CALLER_OLD: &str = r#"
function complexCaller(x) {
  for (let i = 0; i < x; i++) {
    if (i > 5) leaf1();
  }
}
function simpleCaller() { leaf2(); }
function leaf1() { return 1; }
function leaf2() { return 1; }
"#;
const CALLER_NEW: &str = r#"
function cc(x) {
  for (let i = 0; i < x; i++) {
    if (i > 5) l1();
  }
}
function sc() { l2(); }
function l1() { return 1; }
function l2() { return 1; }
"#;

/// TS :132-155 — the chain uniqueRoot → wrapper → leaf: the second round
/// feeds on the first round's resolutions.
const CHAIN_OLD: &str = r#"
function uniqueRoot(x) {
  for (let i = 0; i < x; i++) {
    if (i > 5) wrapper1();
  }
}
function uniqueRoot2() { wrapper2(); }
function wrapper1() { return leaf1(); }
function wrapper2() { return leaf2(); }
function leaf1() { return 1; }
function leaf2() { return 1; }
"#;
const CHAIN_NEW: &str = r#"
function uR(x) {
  for (let i = 0; i < x; i++) {
    if (i > 5) w1();
  }
}
function uR2() { w2(); }
function w1() { return l1(); }
function w2() { return l2(); }
function l1() { return 1; }
function l2() { return 1; }
"#;

/// TS :185-206 — two identical nested functions inside different (unique)
/// parents (the inners renamed so the name lookup stays unique).
const SCOPE_PARENT_OLD: &str = r#"
function outerA(x) {
  for (let i = 0; i < x; i++) { if (i > 5) console.log(i); }
  function innerA() { return 1; }
  return innerA;
}
function outerB() {
  function innerB() { return 1; }
  return innerB;
}
"#;
const SCOPE_PARENT_NEW: &str = r#"
function oA(x) {
  for (let i = 0; i < x; i++) { if (i > 5) console.log(i); }
  function innA() { return 1; }
  return innA;
}
function oB() {
  function innB() { return 1; }
  return innB;
}
"#;

/// TS :235-252 — a unique parent with 3 identical nested children in each
/// version: the scope-parent rung narrows all 3 to the same parent but
/// cannot pick one; the ordinal rung resolves by position.
const ORDINAL_OLD: &str = r#"
function parent(x) {
  for (let i = 0; i < x; i++) { if (i > 5) console.log(i); }
  function child1() { return 1; }
  function child2() { return 1; }
  function child3() { return 1; }
  return [child1, child2, child3];
}
"#;
const ORDINAL_NEW: &str = r#"
function p(x) {
  for (let i = 0; i < x; i++) { if (i > 5) console.log(i); }
  function c1() { return 1; }
  function c2() { return 1; }
  function c3() { return 1; }
  return [c1, c2, c3];
}
"#;

/// TS :277-295 — 2 identical children in v1 but 3 in v2 → the ordinal rung
/// skips for safety.
const COUNTS_OLD: &str = r#"
function parent(x) {
  for (let i = 0; i < x; i++) { if (i > 5) console.log(i); }
  function child1() { return 1; }
  function child2() { return 1; }
  return [child1, child2];
}
"#;
const COUNTS_NEW: &str = r#"
function p(x) {
  for (let i = 0; i < x; i++) { if (i > 5) console.log(i); }
  function c1() { return 1; }
  function c2() { return 1; }
  function c3() { return 1; }
  return [c1, c2, c3];
}
"#;

/// TS :312-343 — the ordinal rung unlocks cascading resolution: the
/// wrappers resolve by ordinal, then their leaves resolve off the newly
/// matched parents (leaves ordered BEFORE their wrappers — the ambiguous
/// insertion order the TS test's `iterations >= 2` expectation implies).
const CASCADE_OLD: &str = r#"
function parent(x) {
  for (let i = 0; i < x; i++) { if (i > 5) console.log(i); }
  function wrapper1() {
    function leafA() { return 1; }
    return leafA;
  }
  function wrapper2() {
    function leafB() { return 1; }
    return leafB;
  }
  return [wrapper1, wrapper2];
}
"#;
const CASCADE_NEW: &str = r#"
function p(x) {
  for (let i = 0; i < x; i++) { if (i > 5) console.log(i); }
  function w1() {
    function lA() { return 1; }
    return lA;
  }
  function w2() {
    function lB() { return 1; }
    return lB;
  }
  return [w1, w2];
}
"#;

/// Two identical top-level functions, both versions: nothing has evidence.
const NO_PARENT: &str = r#"
function a() { return 1; }
function b() { return 1; }
"#;

/// The unevidenced-singleton guard (propagation.ts :145-151): u/v's pool
/// shrinks to one because ANOTHER old function claimed the other candidate
/// — that is not evidence, so neither resolves.
const SINGLETON_OLD: &str = r#"
function u() { return 1; }
function v() { return 1; }
function t() { return 2; }
function w() { return 3; }
"#;
const SINGLETON_NEW: &str = r#"
function n1() { return 1; }
function n2() { return 1; }
function s() { return 2; }
function r() { return 3; }
"#;

/// The contradiction arm (propagation.ts :194-196): the matched-callee
/// constraint filters EVERY candidate out, and the entry keeps its
/// ORIGINAL candidates.
const CONTRADICTION_OLD: &str = r#"
function w() { return helper(); }
function z() { return helper(); }
function helper() { return 7; }
"#;
const CONTRADICTION_NEW: &str = r#"
function W() { return h1(); }
function Z() { return h1(); }
function h1() { return 7; }
function lonely() { return 9; }
"#;

/// The external-refs rung (propagation.ts :307): two module-scope getters
/// that only REFERENCE a matched binding — no callees, no callers, no
/// parent, structurally identical.
const REFS_OLD: &str = r#"
var capA = 1;
var capB = 2;
function getA() { return capA; }
function getB() { return capB; }
"#;
const REFS_NEW: &str = r#"
var cA = 1;
var cB = 2;
function gA() { return cA; }
function gB() { return cB; }
"#;

// ---------------------------------------------------------------------------
// Unit tests
// ---------------------------------------------------------------------------

/// TS :25-71 — the matched-callee rung resolves both wrappers, and the
/// attribution names matchedCallee (no ordinal luck, exp066).
#[test]
fn matched_callee_resolves_both_wrappers_and_attributes_the_rung() {
    with_pair(CALLEE_OLD, CALLEE_NEW, |old_index, new_index| {
        let (mut matches, mut ambiguous) = hash_only_precondition(old_index, new_index);
        assert_eq!(ambiguous.len(), 2, "wrappers must start ambiguous");

        let outcome = run_default(old_index, new_index, &mut matches, &mut ambiguous);

        assert_eq!(outcome.resolved, 2);
        assert_eq!(outcome.iterations, 2, "one fruitless iteration closes");
        assert_eq!(outcome.by_rung.matched_callee, 2);
        assert_eq!(outcome.by_rung.scope_ordinal, 0, "no ordinal luck involved");
        assert_rungs_sum(&outcome);
        assert_eq!(ambiguous.len(), 0, "all ambiguous resolved");
        assert_eq!(
            matches.get(&session_of(old_index.graph, "wrapper1")),
            Some(&session_of(new_index.graph, "w1")),
            "wrapper1 must pair with the wrapper calling the same matched callee"
        );
        assert_eq!(
            matches.get(&session_of(old_index.graph, "wrapper2")),
            Some(&session_of(new_index.graph, "w2"))
        );
        assert_call_graph_consistency(old_index, new_index, &matches);
    });
}

/// TS :74-123 — the matched-caller rung resolves both leaves.
#[test]
fn matched_caller_resolves_both_leaves_and_attributes_the_rung() {
    with_pair(CALLER_OLD, CALLER_NEW, |old_index, new_index| {
        let (mut matches, mut ambiguous) = hash_only_precondition(old_index, new_index);
        assert_eq!(ambiguous.len(), 2, "leaves must start ambiguous");

        let outcome = run_default(old_index, new_index, &mut matches, &mut ambiguous);

        assert_eq!(outcome.resolved, 2);
        assert_eq!(outcome.by_rung.matched_caller, 2);
        assert_rungs_sum(&outcome);
        assert_eq!(ambiguous.len(), 0);
        assert_eq!(
            matches.get(&session_of(old_index.graph, "leaf1")),
            Some(&session_of(new_index.graph, "l1"))
        );
        assert_call_graph_consistency(old_index, new_index, &matches);
    });
}

/// TS :126-179 — the chain: the first round resolves the wrappers off
/// their matched callers, the second round resolves the leaves off the
/// newly matched wrappers. The leaves are ordered BEFORE the wrappers, so
/// the second round is genuinely needed.
#[test]
fn multi_iteration_convergence_when_a_round_unlocks_the_next() {
    with_pair(CHAIN_OLD, CHAIN_NEW, |old_index, new_index| {
        let (mut matches, mut ambiguous) = ordered_precondition(
            old_index,
            new_index,
            &["leaf1", "leaf2", "wrapper1", "wrapper2"],
        );
        assert_eq!(ambiguous.len(), 4);

        let outcome = run_default(old_index, new_index, &mut matches, &mut ambiguous);

        assert_eq!(outcome.resolved, 4);
        assert!(outcome.iterations >= 2, "should take multiple iterations");
        assert_eq!(outcome.by_rung.matched_caller, 4);
        assert_rungs_sum(&outcome);
        assert_eq!(ambiguous.len(), 0, "all should be resolved");
        assert_call_graph_consistency(old_index, new_index, &matches);
    });
}

/// TS :182-227 — the scope-parent rung resolves the nested inners once
/// their (unique) parents are matched.
#[test]
fn scope_parent_resolves_nested_functions() {
    with_pair(
        SCOPE_PARENT_OLD,
        SCOPE_PARENT_NEW,
        |old_index, new_index| {
            let (mut matches, mut ambiguous) = hash_only_precondition(old_index, new_index);
            assert_eq!(ambiguous.len(), 2, "the inners must start ambiguous");

            let outcome = run_default(old_index, new_index, &mut matches, &mut ambiguous);

            assert_eq!(outcome.resolved, 2);
            assert_eq!(outcome.by_rung.scope_parent, 2);
            assert_rungs_sum(&outcome);
            assert_eq!(ambiguous.len(), 0);
            assert_eq!(
                matches.get(&session_of(old_index.graph, "innerA")),
                Some(&session_of(new_index.graph, "innA"))
            );
        },
    );
}

/// TS :230-275 — the ordinal rung resolves same-count siblings by
/// position under the matched parent; the last sibling's pool is
/// injectivity-shrunk to a singleton that scope-parent CONFIRMS, so the
/// attribution splits 2 ordinal / 1 parent (TS :644-647 documents exactly
/// this).
#[test]
fn scope_ordinal_resolves_same_count_siblings_by_position() {
    with_pair(ORDINAL_OLD, ORDINAL_NEW, |old_index, new_index| {
        let (mut matches, mut ambiguous) = hash_only_precondition(old_index, new_index);
        assert_eq!(ambiguous.len(), 3, "the children must start ambiguous");

        let outcome = run_default(old_index, new_index, &mut matches, &mut ambiguous);

        assert_eq!(outcome.resolved, 3);
        assert_eq!(outcome.by_rung.scope_ordinal, 2);
        assert_eq!(outcome.by_rung.scope_parent, 1);
        assert_rungs_sum(&outcome);
        assert_eq!(ambiguous.len(), 0, "all should be resolved");
        // Position pairing: child N must pair with c N.
        for (old_name, new_name) in [("child1", "c1"), ("child2", "c2"), ("child3", "c3")] {
            assert_eq!(
                matches.get(&session_of(old_index.graph, old_name)),
                Some(&session_of(new_index.graph, new_name)),
                "{old_name} must pair by ordinal position"
            );
        }
        assert_call_graph_consistency(old_index, new_index, &matches);
    });
}

/// TS :277-311 — sibling counts differ between versions → the ordinal rung
/// skips for safety and NOTHING resolves.
#[test]
fn scope_ordinal_skips_when_sibling_counts_differ() {
    with_pair(COUNTS_OLD, COUNTS_NEW, |old_index, new_index| {
        let (mut matches, mut ambiguous) = hash_only_precondition(old_index, new_index);
        let before = ambiguous.snapshot();

        let outcome = run_default(old_index, new_index, &mut matches, &mut ambiguous);

        assert_eq!(outcome.resolved, 0, "must not resolve when counts differ");
        assert_eq!(outcome.iterations, 1);
        assert_eq!(ambiguous.snapshot(), before, "pools must stay untouched");
    });
}

/// TS :369-392 — the ordinal rung cannot fire without a matched parent.
#[test]
fn scope_ordinal_does_not_fire_without_a_matched_parent() {
    with_pair(NO_PARENT, NO_PARENT, |old_index, new_index| {
        let (mut matches, mut ambiguous) = hash_only_precondition(old_index, new_index);
        assert_eq!(ambiguous.len(), 2);
        assert!(matches.is_empty(), "nothing matched at hash-only");
        let before = ambiguous.snapshot();

        let outcome = run_default(old_index, new_index, &mut matches, &mut ambiguous);

        assert_eq!(outcome.resolved, 0, "no parent → no ordinal matching");
        assert_eq!(outcome.iterations, 1, "stops after one fruitless iteration");
        assert_eq!(ambiguous.snapshot(), before);
    });
}

/// TS :456-482 — nothing ambiguous: the zero-iteration early return.
#[test]
fn does_nothing_when_there_are_no_ambiguous_functions() {
    with_pair(NO_PARENT, NO_PARENT, |old_index, new_index| {
        let mut matches = HashMap::new();
        matches.insert(
            session_of(old_index.graph, "a"),
            session_of(new_index.graph, "a"),
        );
        matches.insert(
            session_of(old_index.graph, "b"),
            session_of(new_index.graph, "b"),
        );
        let mut ambiguous = AmbiguousMatches::new();

        let outcome = run_default(old_index, new_index, &mut matches, &mut ambiguous);

        assert_eq!(outcome.resolved, 0);
        assert_eq!(outcome.iterations, 0, "should skip when nothing ambiguous");
    });
}

/// TS :484-512 — the iteration cap is respected (the run reports
/// `maxIterations` when the cap stops the loop, propagation.ts :109).
#[test]
fn respects_the_max_iterations_option() {
    with_pair(CALLEE_OLD, CALLEE_NEW, |old_index, new_index| {
        let (mut matches, mut ambiguous) = hash_only_precondition(old_index, new_index);

        let outcome = propagate(
            &mut matches,
            &mut ambiguous,
            old_index,
            new_index,
            PropagationOptions {
                max_iterations: Some(1),
                external_ref_evidence: None,
            },
        );

        assert_eq!(outcome.iterations, 1);
        assert_eq!(outcome.resolved, 2, "both wrappers close in round 1");
    });
}

/// propagation.ts :145-151 — a pool that shrank to one candidate purely
/// because another old function claimed the rest is NOT evidence: the
/// resolution is refused (it would be an order-dependent guess).
#[test]
fn an_unevidenced_singleton_is_not_a_match() {
    with_pair(SINGLETON_OLD, SINGLETON_NEW, |old_index, new_index| {
        let mut matches = HashMap::new();
        matches.insert(
            session_of(old_index.graph, "t"),
            session_of(new_index.graph, "s"),
        );
        // The hand-set claim: w holds n1, so u/v's pool shrinks by
        // injectivity alone. (w's own hash partner r is left unmatched —
        // propagation never validates the input pairs.)
        matches.insert(
            session_of(old_index.graph, "w"),
            session_of(new_index.graph, "n1"),
        );
        let mut ambiguous = AmbiguousMatches::from_pairs(vec![
            (
                session_of(old_index.graph, "u"),
                vec![
                    session_of(new_index.graph, "n1"),
                    session_of(new_index.graph, "n2"),
                ],
            ),
            (
                session_of(old_index.graph, "v"),
                vec![
                    session_of(new_index.graph, "n1"),
                    session_of(new_index.graph, "n2"),
                ],
            ),
        ]);
        let before = ambiguous.snapshot();

        let outcome = run_default(old_index, new_index, &mut matches, &mut ambiguous);

        assert_eq!(outcome.resolved, 0, "injectivity alone is not evidence");
        assert_eq!(outcome.iterations, 1);
        assert_eq!(ambiguous.snapshot(), before);
    });
}

/// propagation.ts :194-196 — a constraint WITH evidence that filters every
/// candidate out is a contradiction: the entry keeps its ORIGINAL
/// candidates (a weaker strategy must not match what a stronger rejected).
#[test]
fn a_contradiction_keeps_the_original_candidates() {
    with_pair(
        CONTRADICTION_OLD,
        CONTRADICTION_NEW,
        |old_index, new_index| {
            let (mut matches, mut ambiguous) = hash_only_precondition(old_index, new_index);
            // Overwrite helper's hash-correct pair: the matched callee is
            // `lonely`, which NO candidate calls.
            matches.insert(
                session_of(old_index.graph, "helper"),
                session_of(new_index.graph, "lonely"),
            );
            assert_eq!(ambiguous.len(), 2);
            let before = ambiguous.snapshot();

            let outcome = run_default(old_index, new_index, &mut matches, &mut ambiguous);

            assert_eq!(outcome.resolved, 0);
            assert_eq!(outcome.iterations, 1);
            assert_eq!(ambiguous.snapshot(), before);
        },
    );
}

/// propagation.ts :307-329 — the external-refs rung: the getters only
/// REFERENCE a matched binding, so the other rungs are silent and the ref
/// evidence is the only discriminating signal. Without the evidence (or
/// without confirmed ref matches) nothing resolves.
#[test]
fn external_ref_evidence_resolves_reference_only_functions() {
    with_pair(REFS_OLD, REFS_NEW, |old_index, new_index| {
        let (mut matches, mut ambiguous) = hash_only_precondition(old_index, new_index);
        assert_eq!(ambiguous.len(), 2, "the getters must start ambiguous");

        // Control 1: no evidence at all — nothing resolves.
        let control = run_default(old_index, new_index, &mut matches, &mut ambiguous);
        assert_eq!(control.resolved, 0);
        assert_eq!(control.iterations, 1);

        // Control 2: ref data but no confirmed ref matches — the expected
        // id list is empty, so the rung abstains.
        let no_ref_matches = ExternalRefEvidence {
            old_refs: BTreeMap::from([(
                session_of(old_index.graph, "getA"),
                BTreeSet::from(["module:capA".to_string()]),
            )]),
            new_refs: BTreeMap::from([(
                session_of(new_index.graph, "gA"),
                BTreeSet::from(["module:cA".to_string()]),
            )]),
            ref_matches: BTreeMap::new(),
        };
        let control = propagate(
            &mut matches,
            &mut ambiguous,
            old_index,
            new_index,
            PropagationOptions {
                max_iterations: None,
                external_ref_evidence: Some(no_ref_matches),
            },
        );
        assert_eq!(control.resolved, 0);

        // The real evidence: both bindings matched (the union of confirmed
        // binding matches the TS builder hands over).
        let evidence = ExternalRefEvidence {
            old_refs: BTreeMap::from([
                (
                    session_of(old_index.graph, "getA"),
                    BTreeSet::from(["module:capA".to_string()]),
                ),
                (
                    session_of(old_index.graph, "getB"),
                    BTreeSet::from(["module:capB".to_string()]),
                ),
            ]),
            new_refs: BTreeMap::from([
                (
                    session_of(new_index.graph, "gA"),
                    BTreeSet::from(["module:cA".to_string()]),
                ),
                (
                    session_of(new_index.graph, "gB"),
                    BTreeSet::from(["module:cB".to_string()]),
                ),
            ]),
            ref_matches: BTreeMap::from([
                ("module:capA".to_string(), "module:cA".to_string()),
                ("module:capB".to_string(), "module:cB".to_string()),
            ]),
        };
        let outcome = propagate(
            &mut matches,
            &mut ambiguous,
            old_index,
            new_index,
            PropagationOptions {
                max_iterations: None,
                external_ref_evidence: Some(evidence),
            },
        );

        assert_eq!(outcome.resolved, 2);
        assert_eq!(outcome.by_rung.external_refs, 2);
        assert_rungs_sum(&outcome);
        assert_eq!(ambiguous.len(), 0);
        assert_eq!(
            matches.get(&session_of(old_index.graph, "getA")),
            Some(&session_of(new_index.graph, "gA")),
            "the getter must pair with the getter referencing the same matched binding"
        );
    });
}

/// TS :312-367 — the ordinal rung unlocks cascading resolution: the
/// wrappers resolve by ordinal in round 1 (the second wrapper's pool is
/// injectivity-shrunk to the singleton its own scope-parent rung then
/// CONFIRMS), and the leaves resolve off the newly matched parents in
/// round 2.
#[test]
fn ordinal_matching_unlocks_cascading_resolution() {
    with_pair(CASCADE_OLD, CASCADE_NEW, |old_index, new_index| {
        let (mut matches, mut ambiguous) = ordered_precondition(
            old_index,
            new_index,
            &["leafA", "leafB", "wrapper1", "wrapper2"],
        );
        assert_eq!(ambiguous.len(), 4, "wrappers and leaves start ambiguous");

        let outcome = run_default(old_index, new_index, &mut matches, &mut ambiguous);

        assert_eq!(outcome.resolved, 4);
        assert_eq!(outcome.iterations, 3, "rounds: wrappers, leaves, close");
        assert_eq!(outcome.by_rung.scope_ordinal, 1);
        assert_eq!(outcome.by_rung.scope_parent, 3);
        assert_rungs_sum(&outcome);
        assert_eq!(ambiguous.len(), 0, "all should be resolved");
        assert_call_graph_consistency(old_index, new_index, &matches);
    });
}

/// TS :394-421 and :514-537 — after propagation every matched pair must be
/// call-graph consistent.
#[test]
fn maintains_call_graph_consistency_after_ordinal_matching() {
    with_pair(ORDINAL_OLD, ORDINAL_NEW, |old_index, new_index| {
        let (mut matches, mut ambiguous) = hash_only_precondition(old_index, new_index);
        run_default(old_index, new_index, &mut matches, &mut ambiguous);
        assert_call_graph_consistency(old_index, new_index, &matches);
    });
}

/// The rung keys' spellings are the artifact dumps' counter keys (the TS
/// `keyof PropagationRungCounts`) — the WP3 vote consumers read them.
#[test]
fn the_rung_keys_carry_the_ts_spellings() {
    use crate::propagation::PropagationRung;
    assert_eq!(PropagationRung::MatchedCallee.as_str(), "matchedCallee");
    assert_eq!(PropagationRung::MatchedCaller.as_str(), "matchedCaller");
    assert_eq!(PropagationRung::ScopeParent.as_str(), "scopeParent");
    assert_eq!(PropagationRung::ExternalRefs.as_str(), "externalRefs");
    assert_eq!(PropagationRung::ScopeOrdinal.as_str(), "scopeOrdinal");
}

// ---------------------------------------------------------------------------
// The frozen TS probe (parity)
// ---------------------------------------------------------------------------

/// The frozen probe's post state, compared field by field.
#[test]
fn the_frozen_ts_probe_reproduces() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../test/parity/wp21-propagation-frozen.json"
    );
    let probe: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(path).expect("probe JSON exists"))
            .expect("probe JSON parses");

    let old_code = probe["old"].as_str().expect("old text");
    let new_code = probe["new"].as_str().expect("new text");
    with_pair(old_code, new_code, |old_index, new_index| {
        let mut matches: HashMap<String, String> = probe["precondition"]["matches"]
            .as_array()
            .expect("matches pairs")
            .iter()
            .map(|pair| {
                (
                    pair[0].as_str().expect("old id").to_string(),
                    pair[1].as_str().expect("new id").to_string(),
                )
            })
            .collect();
        let mut ambiguous = AmbiguousMatches::from_pairs(
            probe["precondition"]["ambiguous"]
                .as_array()
                .expect("ambiguous entries")
                .iter()
                .map(|entry| {
                    (
                        entry[0].as_str().expect("old id").to_string(),
                        entry[1]
                            .as_array()
                            .expect("candidates")
                            .iter()
                            .map(|cand| cand.as_str().expect("candidate id").to_string())
                            .collect(),
                    )
                })
                .collect(),
        );

        let outcome = run_default(old_index, new_index, &mut matches, &mut ambiguous);

        let post = &probe["post"];
        assert_eq!(
            outcome.resolved,
            post["resolved"].as_u64().expect("resolved") as usize
        );
        assert_eq!(
            outcome.iterations,
            post["iterations"].as_u64().expect("iterations") as usize
        );
        assert_eq!(
            outcome.by_rung.matched_callee,
            post["byRung"]["matchedCallee"].as_u64().expect("rung") as usize
        );
        assert_eq!(
            outcome.by_rung.matched_caller,
            post["byRung"]["matchedCaller"].as_u64().expect("rung") as usize
        );
        assert_eq!(
            outcome.by_rung.scope_parent,
            post["byRung"]["scopeParent"].as_u64().expect("rung") as usize
        );
        assert_eq!(
            outcome.by_rung.external_refs,
            post["byRung"]["externalRefs"].as_u64().expect("rung") as usize
        );
        assert_eq!(
            outcome.by_rung.scope_ordinal,
            post["byRung"]["scopeOrdinal"].as_u64().expect("rung") as usize
        );
        assert_rungs_sum(&outcome);

        // The mutated maps: the match SET (order-normalized — the TS map is
        // insertion-ordered, the comparison sorts) and the ambiguous map
        // INCLUDING its entry order (the TS updates in place, so the
        // survivor order is part of the output).
        let frozen_matches: BTreeMap<String, String> = post["matches"]
            .as_array()
            .expect("post matches")
            .iter()
            .map(|pair| {
                (
                    pair[0].as_str().expect("old id").to_string(),
                    pair[1].as_str().expect("new id").to_string(),
                )
            })
            .collect();
        assert_eq!(normalized_matches(&matches), frozen_matches);
        let frozen_ambiguous: Vec<(String, Vec<String>)> = post["ambiguous"]
            .as_array()
            .expect("post ambiguous")
            .iter()
            .map(|entry| {
                (
                    entry[0].as_str().expect("old id").to_string(),
                    entry[1]
                        .as_array()
                        .expect("candidates")
                        .iter()
                        .map(|cand| cand.as_str().expect("candidate id").to_string())
                        .collect(),
                )
            })
            .collect();
        assert_eq!(ambiguous.into_pairs(), frozen_ambiguous);

        assert_call_graph_consistency(old_index, new_index, &matches);
    });
}
