//! The TS truth table (test/parity/wp51-stems.json, generated by
//! test/parity/wp51-stems-probe.ts from the TS's own regex literals and
//! function bodies) — every row must agree field for field.

use super::{
    accept_proposed_name, has_leading_stopword, has_minted_number, is_bad_stem, stem_of,
    to_kebab_case,
};
use serde_json::Value;

const VECTORS: &str = include_str!("../../../../../test/parity/wp51-stems.json");

#[test]
fn every_ts_vector_agrees() {
    let rows: Vec<Value> = serde_json::from_str(VECTORS).expect("vectors parse");
    assert!(rows.len() > 100, "the probe's name list");
    let mut failures = Vec::new();
    for row in &rows {
        let name = row["name"].as_str().expect("name");
        let got = serde_json::json!({
            "name": name,
            "kebab": to_kebab_case(name),
            "accept": accept_proposed_name(name),
            "badStem": is_bad_stem(name),
            "minted": has_minted_number(name),
            "stopword": has_leading_stopword(name),
            "stemOf": stem_of(name),
        });
        if &got != row {
            failures.push(format!("ts {row}\n   rust {got}"));
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}

/// The module name's two spellings (docs/design/module-naming.md): the
/// wrapper `init<Name>` and the file `<name>.js` are one name, so reading
/// the wrapper back gives exactly the file stem the answer would.
#[test]
fn a_module_name_round_trips_between_its_wrapper_and_its_file() {
    use super::{module_stem_of_wrapper, module_wrapper_name};
    for (answer, wrapper, file) in [
        ("color-utils", "initColorUtils", "color-utils"),
        (
            "otlp-log-exporter",
            "initOtlpLogExporter",
            "otlp-log-exporter",
        ),
        ("sha256-hasher", "initSha256Hasher", "sha256-hasher"),
        (
            "tmux_setup_dialog",
            "initTmuxSetupDialog",
            "tmux-setup-dialog",
        ),
    ] {
        let camel = accept_proposed_name(answer).expect("accepted");
        assert_eq!(module_wrapper_name(&camel), wrapper);
        assert_eq!(module_stem_of_wrapper(wrapper).as_deref(), Some(file));
    }
    // Not a module name: a wave's own `initialize…` / `setup…` answer, a
    // minified name, a bare `init`, or a rest the name check refuses.
    for name in [
        "initializeHttpErrorHandling",
        "setupApp",
        "Ab",
        "init",
        "initUtils",
        "initFoo17",
    ] {
        assert_eq!(module_stem_of_wrapper(name), None, "{name}");
    }
}
