//! The TS truth table (test/parity/wp51-stems.json, generated by
//! test/parity/wp51-stems-probe.ts from the TS's own regex literals and
//! function bodies) — every row must agree field for field.

use super::{
    accept_proposed_name, has_leading_stopword, has_minted_number, is_bad_stem, stem_of,
    to_kebab_case,
};
use serde_json::Value;

const VECTORS: &str = include_str!("../../../../../test/parity/wp51-stems.json");

#[test]
fn every_ts_vector_agrees() {
    let rows: Vec<Value> = serde_json::from_str(VECTORS).expect("vectors parse");
    assert!(rows.len() > 100, "the probe's name list");
    let mut failures = Vec::new();
    for row in &rows {
        let name = row["name"].as_str().expect("name");
        let got = serde_json::json!({
            "name": name,
            "kebab": to_kebab_case(name),
            "accept": accept_proposed_name(name),
            "badStem": is_bad_stem(name),
            "minted": has_minted_number(name),
            "stopword": has_leading_stopword(name),
            "stemOf": stem_of(name),
        });
        if &got != row {
            failures.push(format!("ts {row}\n   rust {got}"));
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}
