/**
 * R4 (cache-key bit-parity): emit the adversarial (typed request, expected
 * key) vectors the Rust cache module must reproduce byte-for-byte. The
 * vectors commit under test/parity/cache-key-vectors.jsonl; the Rust test
 * re-derives every key from the typed request. Generated by the TS side's
 * own canonicalJson/cacheKeyOf — the keys are the GROUND TRUTH by
 * construction (they are what a TS cache write used).
 */
import { writeFileSync } from "node:fs";
import {
  cacheKeyOf,
  type CacheKeyParams
} from "../../src/llm/cached-provider.js";
import type { BatchRenameRequest } from "../../src/llm/types.js";

const params: CacheKeyParams = {
  model: "openai/gpt-oss-20b",
  temperature: 0,
  maxTokens: 6000,
  reasoningEffort: "low"
};

const base: BatchRenameRequest = {
  code: "function f() { return 1; }",
  identifiers: ["f"],
  usedNames: new Set(["console"]),
  calleeSignatures: [],
  callsites: []
};

const cases: Array<[string, CacheKeyParams, BatchRenameRequest]> = [
  ["plain", params, base],
  [
    "unicode-identifier",
    params,
    {
      ...base,
      identifiers: ["café", "中文", "😀x"],
      code: "var café = 中文 + 1;"
    }
  ],
  [
    "empty-set-and-arrays",
    params,
    { ...base, usedNames: new Set(), calleeSignatures: [], callsites: [] }
  ],
  [
    "undefined-optionals-absent",
    params,
    base // no optionals set at all
  ],
  [
    "retry-fields-present",
    params,
    {
      ...base,
      isRetry: true,
      previousAttempt: { f: "g" },
      failures: {
        duplicates: ["h"],
        invalid: [],
        missing: ["i"],
        unchanged: []
      }
    }
  ],
  [
    "prompt-override-fields",
    params,
    {
      ...base,
      promptBody: "body text",
      userPrompt: "user text",
      systemPrompt: "sys"
    }
  ],
  [
    "prior-fields",
    params,
    {
      ...base,
      priorVersionCode: "function g() {}",
      priorVersionNames: ["g", "h"],
      priorNameHints: { f: "g" },
      alreadyRenamed: { f: "g" }
    }
  ],
  ["params-with-absent-max-tokens", { model: "m", temperature: 0 }, base],
  [
    "params-with-absent-reasoning-effort",
    { model: "m", temperature: 0, maxTokens: 100 },
    base
  ],
  [
    "callees-with-params",
    params,
    {
      ...base,
      calleeSignatures: [
        { name: "helper", params: ["a", "b"] },
        { name: "中文Fn", params: [] }
      ],
      callsites: ["helper(1, 2)", "中文Fn()"]
    }
  ]
];

// The order-different pair: append BOTH spellings with the SAME expected key.
const orderPair: BatchRenameRequest = {
  ...base,
  usedNames: new Set(["b", "a", "c"])
};
const orderPairReordered: BatchRenameRequest = {
  ...base,
  usedNames: new Set(["c", "b", "a"])
};

const rows: string[] = [];
const push = (name: string, p: CacheKeyParams, r: BatchRenameRequest) => {
  rows.push(
    JSON.stringify({
      name,
      params: p,
      request: {
        ...r,
        usedNames: [...r.usedNames]
      },
      expectedKey: cacheKeyOf(r, p)
    })
  );
};

for (const [name, p, r] of cases) {
  push(name, p, r);
}
// The set-order pair: SAME members, different insertion orders, ONE key.
const keyA = cacheKeyOf(orderPair, params);
const keyB = cacheKeyOf(orderPairReordered, params);
if (keyA !== keyB) {
  throw new Error(
    "canonicalization is order-sensitive over Set members — the cache contract is broken"
  );
}
push("set-order-a", params, orderPair);
push("set-order-b-same-key-as-a", params, orderPairReordered);

writeFileSync("test/parity/cache-key-vectors.jsonl", `${rows.join("\n")}\n`);
console.log(
  `wrote ${rows.length} vectors to test/parity/cache-key-vectors.jsonl`
);
