/**
 * Runnable scaffolding for a --split-runnable output tree.
 *
 * The emitted graph loads and runs under Node, but a Bun bundle leaves two
 * loose ends between "loads" and "runs standalone":
 *   - a few packages Bun kept external (`require("ws")`, `require("ajv")`)
 *     that must come from node_modules, and
 *   - `using`/`await using` declarations that older Node cannot parse.
 *
 * This writes a self-contained runner (`run.cjs`) that boots the entry —
 * feature-detecting `using` support and stripping it only when unsupported
 * — plus a `package.json` listing the detected externals (so `npm install`
 * provisions them) and a short `RUNNABLE.md`. The result: an unpacked
 * humanified tree you can `npm install && node run.cjs` and actually run.
 */

import { readdir, readFile, writeFile } from "node:fs/promises";
import { builtinModules } from "node:module";
import * as path from "node:path";

export const RUNNER_FILENAME = "run.cjs";
export const SCAFFOLD_README = "RUNNABLE.md";

const BUILTINS = new Set<string>(builtinModules);

/** Bare require/import specifiers, capturing the specifier. */
const SPECIFIER_RE = /(?:require|import)\s*\(\s*["']([^"']+)["']\s*\)/g;

function isBuiltin(spec: string): boolean {
  const bare = spec.startsWith("node:") ? spec.slice(5) : spec;
  // `fs/promises`, `stream/web`, … are builtin subpaths.
  return BUILTINS.has(bare) || BUILTINS.has(bare.split("/")[0]);
}

/** The installable package name for a specifier: the scope+name, dropping
 * any deep subpath (`ajv/dist/x` → `ajv`, `@s/p/q` → `@s/p`). */
function packageName(spec: string): string {
  const parts = spec.split("/");
  return spec.startsWith("@") ? parts.slice(0, 2).join("/") : parts[0];
}

/**
 * The external npm packages required across `contents` — bare specifiers
 * that are neither Node builtins nor relative/absolute paths — as a sorted,
 * de-duplicated list of installable package names.
 */
export function externalPackagesFrom(contents: Iterable<string>): string[] {
  const found = new Set<string>();
  for (const text of contents) {
    for (const m of text.matchAll(SPECIFIER_RE)) {
      const spec = m[1];
      if (spec.startsWith(".") || spec.startsWith("/")) continue;
      // A scheme prefix (node:, bun:, http:, data:, …) is a runtime builtin
      // or URL, never an installable npm package. Bun-only modules like
      // `bun:jsc` are guarded behind `typeof Bun` checks at runtime.
      if (spec.includes(":")) continue;
      if (isBuiltin(spec)) continue;
      found.add(packageName(spec));
    }
  }
  return [...found].sort();
}

async function jsFilesUnder(dir: string): Promise<string[]> {
  const out: string[] = [];
  const walk = async (d: string): Promise<void> => {
    for (const entry of await readdir(d, { withFileTypes: true })) {
      const full = path.join(d, entry.name);
      if (entry.isDirectory()) {
        if (entry.name === "node_modules") continue;
        await walk(full);
      } else if (entry.name.endsWith(".js") || entry.name.endsWith(".cjs")) {
        out.push(full);
      }
    }
  };
  await walk(dir);
  return out;
}

/** Scan an emitted tree on disk for the external packages it requires. */
export async function detectExternalPackages(dir: string): Promise<string[]> {
  const files = await jsFilesUnder(dir);
  const contents = await Promise.all(files.map((f) => readFile(f, "utf-8")));
  return externalPackagesFrom(contents);
}

function runnerSource(entryFile: string): string {
  return `#!/usr/bin/env node
// Auto-generated by humanify --split-runnable. Boots the unpacked tree:
//   node ${RUNNER_FILENAME} --version
// Run \`npm install\` here first if this tree requires external packages.
const Module = require("node:module");
const path = require("node:path");

// \`using\`/\`await using\` is Stage-3 syntax the source bundle may use.
// Strip it only on Node versions that cannot parse it (a no-op elsewhere).
let usingSupported = true;
try {
  new Function(
    "async function _(){ using x = { [Symbol.dispose](){} }; await using y = { async [Symbol.asyncDispose](){} }; }"
  );
} catch {
  usingSupported = false;
}
if (!usingSupported) {
  const compile = Module.prototype._compile;
  Module.prototype._compile = function (content, filename) {
    const stripped = content
      .replace(/\\bawait\\s+using\\b/g, "const")
      .replace(/\\busing\\b(?=\\s+[A-Za-z_$])/g, "const");
    return compile.call(this, stripped, filename);
  };
}

const entry = path.join(__dirname, ${JSON.stringify(entryFile)});
process.argv = [process.argv[0], entry, ...process.argv.slice(2)];
require(entry);
`;
}

function packageJsonSource(externals: string[]): string {
  const dependencies: Record<string, string> = {};
  for (const name of externals) dependencies[name] = "*";
  return `${JSON.stringify(
    {
      name: "humanified-runnable",
      private: true,
      description: "Unpacked, humanified, split bundle — runnable under Node.",
      scripts: { start: `node ${RUNNER_FILENAME}` },
      dependencies
    },
    null,
    2
  )}\n`;
}

function readmeSource(entryFile: string, externals: string[]): string {
  const deps = externals.length
    ? `This tree requires ${externals.length} external package(s): ${externals.join(", ")}.\n` +
      'Versions are best-effort ("*"); pin them if a package\'s internal ' +
      "layout must match the original bundle.\n\n" +
      "```sh\nnpm install\n```\n\n"
    : "This tree needs no external packages.\n\n";
  return `# Running this tree

${deps}Then boot it:

\`\`\`sh
node ${RUNNER_FILENAME} --version
node ${RUNNER_FILENAME} --help
\`\`\`

\`${RUNNER_FILENAME}\` loads \`${entryFile}\`, which requires every module in
the tree (split runtime files + re-linked Bun factory modules). It strips
\`using\` declarations only on Node versions that cannot parse them.
`;
}

/** Write the runner, package.json, and README into an emitted tree. */
export async function writeRunnableScaffold(
  outputDir: string,
  entryFile: string,
  externals: string[]
): Promise<void> {
  await writeFile(
    path.join(outputDir, RUNNER_FILENAME),
    runnerSource(entryFile)
  );
  await writeFile(
    path.join(outputDir, "package.json"),
    packageJsonSource(externals)
  );
  await writeFile(
    path.join(outputDir, SCAFFOLD_README),
    readmeSource(entryFile, externals)
  );
}
