//! The prior-side cache's two pins, in ONE test (the parse counter is a
//! process global, so the pin must not race a sibling test on another
//! thread — a single #[test] in its own integration binary cannot):
//!
//! 1. **The parse-count pin**: `humanify match` builds the prior side
//!    ONCE per run — one parse of the prior text, however many files the
//!    work dir holds. The single-call design the verb grew from (the
//!    pipeline's per-file `match_prior_version`) reparsed the whole prior
//!    per file — twice per file in the default fast schedule — which on a
//!    raw bun-bundle tree (a runtime plus hundreds of vendor files,
//!    against a ~33MB prior) turned minutes of matching into hours of
//!    rebuilding the same index. Pinning the count keeps the amortization
//!    from silently regressing.
//! 2. **The byte pin**: the refactor that introduced the cache must be
//!    behavior-preserving, and the dump is the verb's whole output — a
//!    golden, generated by the pre-refactor binary, holds its exact bytes.
//!    Only the two `meta` PATH fields are normalized away (they embed the
//!    scratch dir and would differ run to run; no matching decision reads
//!    them). Regenerate deliberately, after a dump-shape change, with
//!    `MATCH_PIN_WRITE_GOLDEN=1 cargo test -p humanify-cli --test
//!    match_prior_side_cache` — and re-check the bytes against a binary
//!    from before the change you are about to commit.

use serde_json::Value;

use humanify_cli::match_verb::{MatchVerbArgs, match_dump};
use humanify_core::prior::{prior_parse_count, reset_prior_parse_count};

/// A bundle of four old-shape factories (`function (…) {…}` at statement
/// level — the shape the raw unpack tree does not parse standalone) over
/// the Bun CJS bundle head (`createRequire` alias plus the `x` factory
/// helper — the shape `detect` selects the Bun adapter on), one of which
/// (`pick3`) has NO counterpart in the prior, so the golden carries
/// unmatched rows as well as pairs.
const BUNDLE: &str = concat!(
    "import{createRequire as Glq}from\"node:module\";\n",
    "var m6=Glq(import.meta.url);\n",
    "var x=(I,A)=>()=>(A||I((A={exports:{}}).exports,A),A.exports);\n",
    "var mod_0=x(function(exports,module){module.exports={pick0:function(v){return v+0}};});\n",
    "var mod_1=x(function(exports,module){module.exports={pick1:function(v){return v+1}};});\n",
    "var mod_2=x(function(exports,module){module.exports={pick2:function(v){return v+2}};});\n",
    "var mod_3=x(function(exports,module){module.exports={pick3:function(v){return v+3}};});\n",
    "var run=mod_0().pick0(1);\n"
);

/// The prior release's vendor files for three of the four factories, as
/// the finish ships them (`exports.f = __commonJS(F)`), concatenated into
/// the one prior text the verb takes.
const PRIOR: &str = concat!(
    "const { __commonJS } = require(\"../.humanify/__bun-runtime.js\");\n",
    "exports.f = __commonJS(function (exports, module) {\n",
    "  module.exports = { pick0: function (v) { return v + 0; } };\n",
    "});\n",
    "exports.f = __commonJS(function (exports, module) {\n",
    "  module.exports = { pick1: function (v) { return v + 1; } };\n",
    "});\n",
    "exports.f = __commonJS(function (exports, module) {\n",
    "  module.exports = { pick2: function (v) { return v + 2; } };\n",
    "});\n"
);

/// A single-file, non-bundle input (the passthrough adapter's regime).
const SINGLE_FILE: &str = "function a(first, second) {\n  return first + second;\n}\n";
const SINGLE_PRIOR: &str = "function a(first, second) {\n  return first + second;\n}\n";

fn temp_dir(tag: &str) -> std::path::PathBuf {
    let dir = std::env::temp_dir().join(format!(
        "humanify-match-prior-cache-{tag}-{}",
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).expect("mkdir fixture dir");
    dir
}

fn write(dir: &std::path::Path, name: &str, text: &str) -> String {
    let path = dir.join(name);
    std::fs::write(&path, text).expect("write fixture");
    path.display().to_string()
}

/// Text formatted through the stage-6 formatter — the no-LLM equivalent
/// of a humanified prior the verb expects.
fn formatted(dir: &std::path::Path, name: &str, code: &str) -> String {
    let text =
        humanify_core::format::format(code, &humanify_core::format::FormatOptions::default())
            .expect("the fixture formats");
    write(dir, name, &text)
}

/// Run the verb over `input`/`prior` under `tag`'s scratch dir.
fn dump(dir: &std::path::Path, input: &str, prior: &str) -> Value {
    match_dump(&MatchVerbArgs {
        input,
        prior_version: prior,
        sequential: false,
        bundler: None,
        minifier: None,
        webcrack_shim: None,
        work_dir: Some(&dir.join("work").display().to_string()),
        keep_work_dir: true,
    })
    .expect("the match verb runs")
}

/// The dump with the two PATH fields replaced by placeholders — the only
/// bytes that vary run to run (they embed the scratch dir).
fn normalized(dump: &Value) -> String {
    let mut dump = dump.clone();
    let meta = dump
        .get_mut("meta")
        .expect("the dump has meta")
        .as_object_mut()
        .expect("meta is an object");
    meta.insert("input".into(), Value::String("<input>".into()));
    meta.insert("prior".into(), Value::String("<prior>".into()));
    let text = serde_json::to_string_pretty(&dump).expect("the dump serializes");
    format!("{text}\n")
}

#[test]
fn the_prior_side_is_built_once_and_the_dump_bytes_hold() {
    // ── the parse-count pin, single-file first ───────────────────────────
    // One file, one prior parse. (The pre-cache code parsed TWICE even
    // here: the fast schedule's side thread and its main-thread re-parse.)
    let dir = temp_dir("single");
    let input = write(&dir, "input.js", SINGLE_FILE);
    let prior = formatted(&dir, "prior.js", SINGLE_PRIOR);
    reset_prior_parse_count();
    let single = dump(&dir, &input, &prior);
    assert_eq!(single["schemaVersion"], 1, "the single-file shape");
    assert_eq!(
        prior_parse_count(),
        1,
        "one fresh file means ONE parse of the prior text"
    );
    let _ = std::fs::remove_dir_all(&dir);

    // ── the parse-count pin, the multi-file raw-bundle regime ────────────
    // Five sections (runtime plus four wrapped vendor files), still ONE
    // parse of the prior: the prior side is the run's shared state.
    let dir = temp_dir("multi");
    let input = write(&dir, "input.js", BUNDLE);
    let prior = formatted(&dir, "prior.js", PRIOR);
    reset_prior_parse_count();
    let multi = dump(&dir, &input, &prior);
    assert_eq!(
        prior_parse_count(),
        1,
        "the prior side is built once per run, not per file"
    );
    assert_eq!(
        multi["schemaVersion"], 2,
        "the raw bundle is the multi-file shape"
    );
    assert_eq!(
        multi["meta"]["wrappedFactoryFiles"]
            .as_array()
            .expect("wrapped list")
            .len(),
        4,
        "every vendor factory was wrapped"
    );

    // ── the byte pin ─────────────────────────────────────────────────────
    // The golden was generated by the PRE-CACHE binary; normalized (only
    // the two path fields) the dump must be byte-identical to it.
    let golden_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/match_prior_side_cache.golden.json");
    let actual = normalized(&multi);
    if std::env::var("MATCH_PIN_WRITE_GOLDEN").is_ok() {
        std::fs::write(&golden_path, &actual).expect("write the golden");
        panic!(
            "golden written to {} — un-set MATCH_PIN_WRITE_GOLDEN and re-run",
            golden_path.display()
        );
    }
    let golden = std::fs::read_to_string(&golden_path).unwrap_or_else(|e| {
        panic!(
            "read {}: {e} (regenerate with MATCH_PIN_WRITE_GOLDEN=1)",
            golden_path.display()
        )
    });
    assert_eq!(
        actual, golden,
        "the dump's bytes are pinned; regenerate the golden only for a \
         DELIBERATE dump-shape change, and re-check against a pre-change \
         binary"
    );
    let _ = std::fs::remove_dir_all(&dir);
}
