[package]
name = "humanify-cli"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "humanify"
path = "src/main.rs"

[dependencies]
humanify-core = { path = "../humanify-core" }
humanify-llm = { path = "../humanify-llm" }
humanify-model = { path = "../humanify-model" }
serde_json.workspace = true
clap.workspace = true
dotenvy.workspace = true

[lints]
workspace = true
