[package]
name = "humanify-core"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
sha2.workspace = true
serde_json.workspace = true
serde.workspace = true
oxc_allocator.workspace = true
oxc_estree.workspace = true
oxc_ast.workspace = true
oxc_parser.workspace = true
oxc_semantic.workspace = true
oxc_span.workspace = true
oxc_syntax.workspace = true
oxc_traverse.workspace = true
humanify-model = { path = "../humanify-model" }

[lints]
workspace = true
