//! Rename-target legality (WP3.1): `isValidRenameTarget` — a legal ASCII
//! identifier, not a reserved word, not a global builtin. TS originals:
//! `src/rename/validated-rename.ts` (the predicate) over
//! `src/llm/validation.ts`'s `isValidIdentifier`, `RESERVED_WORDS` and
//! `GLOBAL_BUILTINS` (WP4.2's module owns the rest of validation.ts; these
//! three are the part validated rename reads, and WP4.2 must reuse them).
//!
//! `GLOBAL_BUILTINS` is DERIVED in the TS (the `globals` package's builtin +
//! nodeBuiltin + shared-node-browser sets, plus a curated host list), so the
//! lists below are GENERATED from the TS at `test/parity/wp31-names.json`
//! (`npx tsx test/parity/wp31-name-probe.mjs`) and the unit test asserts
//! exact equality — a `globals` bump that moves the set reds it.

/// `RESERVED_WORDS`, sorted (byte order).
pub const RESERVED_WORDS: &[&str] = &[
    "Infinity",
    "NaN",
    "arguments",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "export",
    "extends",
    "false",
    "finally",
    "for",
    "function",
    "if",
    "implements",
    "import",
    "in",
    "instanceof",
    "interface",
    "let",
    "new",
    "null",
    "package",
    "private",
    "protected",
    "public",
    "return",
    "static",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "typeof",
    "undefined",
    "var",
    "void",
    "while",
    "with",
    "yield",
];

/// `GLOBAL_BUILTINS`, sorted (byte order).
pub const GLOBAL_BUILTINS: &[&str] = &[
    "$",
    "AbortController",
    "AbortSignal",
    "AggregateError",
    "Array",
    "ArrayBuffer",
    "AsyncDisposableStack",
    "Atomics",
    "BigInt",
    "BigInt64Array",
    "BigUint64Array",
    "Blob",
    "Boolean",
    "BroadcastChannel",
    "Buffer",
    "Bun",
    "ByteLengthQueuingStrategy",
    "CloseEvent",
    "CompressionStream",
    "CountQueuingStrategy",
    "Crypto",
    "CryptoKey",
    "CustomEvent",
    "DOMException",
    "DataView",
    "Date",
    "DecompressionStream",
    "DisposableStack",
    "Error",
    "ErrorEvent",
    "EvalError",
    "Event",
    "EventTarget",
    "File",
    "FinalizationRegistry",
    "Float16Array",
    "Float32Array",
    "Float64Array",
    "FormData",
    "Function",
    "Headers",
    "Infinity",
    "Int16Array",
    "Int32Array",
    "Int8Array",
    "Intl",
    "Iterator",
    "JSON",
    "Map",
    "Math",
    "MessageChannel",
    "MessageEvent",
    "MessagePort",
    "NaN",
    "Navigator",
    "Number",
    "Object",
    "Performance",
    "PerformanceEntry",
    "PerformanceMark",
    "PerformanceMeasure",
    "PerformanceObserver",
    "PerformanceObserverEntryList",
    "PerformanceResourceTiming",
    "Promise",
    "Proxy",
    "RangeError",
    "ReadableByteStreamController",
    "ReadableStream",
    "ReadableStreamBYOBReader",
    "ReadableStreamBYOBRequest",
    "ReadableStreamDefaultController",
    "ReadableStreamDefaultReader",
    "ReferenceError",
    "Reflect",
    "RegExp",
    "Request",
    "Response",
    "Set",
    "SharedArrayBuffer",
    "Storage",
    "String",
    "SubtleCrypto",
    "SuppressedError",
    "Symbol",
    "SyntaxError",
    "TextDecoder",
    "TextDecoderStream",
    "TextEncoder",
    "TextEncoderStream",
    "TransformStream",
    "TransformStreamDefaultController",
    "TypeError",
    "URIError",
    "URL",
    "URLPattern",
    "URLSearchParams",
    "Uint16Array",
    "Uint32Array",
    "Uint8Array",
    "Uint8ClampedArray",
    "WeakMap",
    "WeakRef",
    "WeakSet",
    "WebAssembly",
    "WebSocket",
    "WritableStream",
    "WritableStreamDefaultController",
    "WritableStreamDefaultWriter",
    "atob",
    "btoa",
    "clearImmediate",
    "clearInterval",
    "clearTimeout",
    "console",
    "crypto",
    "decodeURI",
    "decodeURIComponent",
    "define",
    "document",
    "encodeURI",
    "encodeURIComponent",
    "escape",
    "eval",
    "fetch",
    "global",
    "globalThis",
    "importScripts",
    "isFinite",
    "isNaN",
    "jQuery",
    "localStorage",
    "location",
    "navigator",
    "parseFloat",
    "parseInt",
    "performance",
    "postMessage",
    "process",
    "queueMicrotask",
    "self",
    "sessionStorage",
    "setImmediate",
    "setInterval",
    "setTimeout",
    "structuredClone",
    "undefined",
    "unescape",
    "window",
];

/// `isValidIdentifier`: `/^[a-zA-Z_$][a-zA-Z0-9_$]*$/` — ASCII only, so a
/// non-ASCII letter the language would accept is NOT a valid target.
pub fn is_valid_identifier(name: &str) -> bool {
    let mut bytes = name.bytes();
    let Some(first) = bytes.next() else {
        return false;
    };
    (first.is_ascii_alphabetic() || first == b'_' || first == b'$')
        && bytes.all(|b| b.is_ascii_alphanumeric() || b == b'_' || b == b'$')
}

pub fn is_reserved_word(name: &str) -> bool {
    RESERVED_WORDS.binary_search(&name).is_ok()
}

pub fn is_global_builtin(name: &str) -> bool {
    GLOBAL_BUILTINS.binary_search(&name).is_ok()
}

/// `isValidRenameTarget`.
pub fn is_valid_rename_target(name: &str) -> bool {
    is_valid_identifier(name) && !is_reserved_word(name) && !is_global_builtin(name)
}
